# Based on https://github.com/best-of-lists/best-of-update-action/blob/v0.8.5/workflows/update-best-of-list.yml
name: update-best-of-list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4" # Every thursday at 6pm
  push:
    branches:
      - main

jobs:
  lint:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v8.1.0
      - name: Best of list update
        run: uvx best-of generate projects.yaml -g ${{ secrets.GITHUB_TOKEN}}
      - uses: fregante/setup-git-user@v2
      - name: Run prek
        run: uvx prek run -a || uvx prek run -a || true
      - name: Commit changes
        run: |
          git add .
          git commit -m "docs: ${{ env.VERSION  }} [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION  }}
          release_name: "${{ env.VERSION }}"
          body_path: "latest-changes.md"
