# Based on https://github.com/best-of-lists/best-of-update-action/blob/v0.8.5/workflows/update-best-of-list.yml
name: update-best-of-list

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to use for this update"
        required: false
  schedule:
    - cron: "0 18 * * 4" # Every thursday at 6pm
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v8.1.0
      - name: Best of list update
        run: uvx best-of generate projects.yaml -g ${{ secrets.GITHUB_TOKEN}}
      - uses: j178/prek-action@v2.0.3
      - uses: fregante/setup-git-user@v2
      - name: Commit changes
        run: |
          git add .
          git commit -m "docs: ${{ env.VERSION  }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION  }}
          release_name: "${{ env.VERSION }}"
          body_path: "latest-changes.md"
